base_prompt = \
    '''
You have to create various business documents for Instagram for personal use. I will explain the document that you have to generate and its description along with the details I want in it. The Instagram description below was previously generated by you to help you maintain consistency in document generation. Generate documents in a strict MarkDown format, with no other information present in the response.

Instagram Description:

Instagram is a popular social media platform that allows users to share photos, videos, and stories with their followers. Launched in 2010, Instagram quickly gained widespread popularity due to its user-friendly interface and focus on visual content. The platform was acquired by Facebook in 2012 but has since maintained its own distinct identity and features. Instagram is more than just a social media platform—it's a vibrant community where users can connect, create, and be inspired. With features like the feed, Stories, Direct messaging, Explore, IGTV, and Reels, Instagram offers a diverse range of ways to share and discover content. Whether you're a professional photographer, a budding artist, a small business owner, or simply someone who loves to share moments with friends, Instagram provides a platform for you to express yourself and connect with others who share your passions. Join the Instagram community today and start sharing your story with the world!

Key Features:

1. **Feed:** The main feed of Instagram displays photos and videos from accounts that a user follows. Users can like, comment on, and share posts directly from their feed.

2. **Stories:** Instagram Stories are temporary posts that disappear after 24 hours. Users can add photos, videos, text, stickers, and other interactive elements to their Stories, allowing for more dynamic and creative content sharing.

3. **Direct Messaging:** Instagram offers a built-in messaging feature called Direct, allowing users to send private messages, photos, and videos to individuals or groups.

4. **Explore:** The Explore tab on Instagram helps users discover new content and accounts based on their interests and activity. It includes personalized recommendations as well as trending posts and topics.

5. **IGTV:** Instagram TV (IGTV) allows users to upload longer-form videos, up to 10 minutes for regular users and up to 60 minutes for verified accounts. IGTV content is displayed in a vertical format, optimized for mobile viewing.

6. **Reels:** Introduced in 2020, Instagram Reels is a feature for creating and sharing short-form video content, similar to TikTok. Users can add music, effects, and text to their Reels, making it easy to create engaging and entertaining videos.

The document to be generated, along with its information is given below:

Company Name: Instagram
Category of document: {doc_category}.
Document title: {doc_title}.
Document Description: {doc_description}.

Given all of the information above, generate the document {doc_title}.
Note: Here on, do not use Lorem Ipsum or any template text for blank information. Instead, make up the information yourself and maintain consistency in it.
Example - 1: While generating employee contract documents, do not leave the name blank or as "Employee 1". You have to fill these values with simple human names.
Example - 2: While generating financial documents, do not leave the amount values as "Amount" or blank. You have to fill these values with random numbers that make sense.
Example - 3: While generating business documents such as progress reports, do not leave the project name as "Project X". You have to fill these values with realistic project names and provide real status updates.

Generated Document:
'''

# Category of document: Company ByLaws

about_company_prompt = "The About page of a company provides essential information about its identity, mission, history, key personnel, values, and achievements. It typically includes an overview of the company's purpose and goals, a statement of its mission and values, a brief history, information about key team members, its approach to business, customer focus, achievements, community involvement, and contact information. This page serves as a digital introduction, establishing trust and credibility while helping visitors understand the company's ethos and vision."
about_bod_prompt = "The Board of Directors page of a company provides information about the individuals who serve on the company's board. It typically includes an overview of the board's composition, the names and titles of board members, their professional backgrounds, and their contributions to the company. This page serves as a digital introduction to the company's leadership, establishing transparency and trust while helping visitors understand the company's governance structure."
about_shareholders_prompt = "The Shareholders page of a company provides information about the individuals or entities that own shares in the company. It typically includes an overview of the company's ownership structure, the names and titles of major shareholders, their shareholdings, and their contributions to the company. This page serves as a digital introduction to the company's ownership, establishing transparency and trust while helping visitors understand the company's capital structure."
about_dei_prompt = "The Diversity, Equity, and Inclusion (DEI) page of a company provides information about the company's commitment to diversity, equity, and inclusion in the workplace. It typically includes an overview of the company's DEI initiatives, its approach to fostering a diverse and inclusive culture, its commitment to equity and fairness, and its efforts to promote diversity in hiring, retention, and advancement. This page serves as a digital introduction to the company's DEI efforts, establishing transparency and trust while helping visitors understand the company's commitment to social responsibility."

company_bylaws_prompts_list = [
    {
        "doc_category": "Company ByLaws",
        "doc_title": "About Instagram",
        "doc_description": about_company_prompt
    },
    {
        "doc_category": "Company ByLaws",
        "doc_title": "Board of Directors",
        "doc_description": about_bod_prompt
    },
    {
        "doc_category": "Company ByLaws",
        "doc_title": "Shareholders",
        "doc_description": about_shareholders_prompt
    },
    {
        "doc_category": "Company ByLaws",
        "doc_title": "Diversity, Equity, and Inclusion",
        "doc_description": about_dei_prompt
    }
]


# Category of document: Employee Contract

employee_documents_base_prompt = \
    '''
You have to create various business documents for Instagram for personal use. I will explain the document that you have to generate and its description along with the details I want in it. The Instagram description below was previously generated by you to help you maintain consistency in document generation. Generate documents in a strict MarkDown format, with no other information present in the response.

Instagram Description:

Instagram is a popular social media platform that allows users to share photos, videos, and stories with their followers. Launched in 2010, Instagram quickly gained widespread popularity due to its user-friendly interface and focus on visual content. The platform was acquired by Facebook in 2012 but has since maintained its own distinct identity and features. Instagram is more than just a social media platform—it's a vibrant community where users can connect, create, and be inspired. With features like the feed, Stories, Direct messaging, Explore, IGTV, and Reels, Instagram offers a diverse range of ways to share and discover content. Whether you're a professional photographer, a budding artist, a small business owner, or simply someone who loves to share moments with friends, Instagram provides a platform for you to express yourself and connect with others who share your passions. Join the Instagram community today and start sharing your story with the world!

Generate a template for the given document along with the information provided below. The document should be in a strict MarkDown format, with no other information present in the response. Your goal is to generate a document template that can be used for different employees.

Category of document: {doc_category}.
Document title: {doc_title}.
Document Description: {doc_description}.

Note: For any variable information, use a sensible variable name in python format using underscores between words and enclose it in curly braces. For example, if the variable is employee name, use employee_name in curly braces.

Generated Document:
'''

employee_info = [
    {
        "employee_name": "John Doe",
        "employee_salary": "100,000",
        "employee_position": "Software Engineer",
        "employee_start_date": "January 1, 2022",
        "employee_end_date": "December 31, 2022",
        "employee_department": "Engineering"
    },
    {
        "employee_name": "Jane Smith",
        "employee_salary": "80,000",
        "employee_position": "Marketing Specialist",
        "employee_start_date": "February 1, 2022",
        "employee_end_date": "January 31, 2023",
        "employee_department": "Marketing"
    },
    {
        "employee_name": "Michael Johnson",
        "employee_salary": "120,000",
        "employee_position": "Product Manager",
        "employee_start_date": "March 1, 2022",
        "employee_end_date": "February 28, 2023",
        "employee_department": "Product Management"
    },
    {
        "employee_name": "Emily Brown",
        "employee_salary": "90,000",
        "employee_position": "UX Designer",
        "employee_start_date": "April 1, 2022",
        "employee_end_date": "March 31, 2023",
        "employee_department": "Design"
    },
    {
        "employee_name": "David Lee",
        "employee_salary": "110,000",
        "employee_position": "Data Analyst",
        "employee_start_date": "May 1, 2022",
        "employee_end_date": "April 30, 2023",
        "employee_department": "Data Analytics"
    },
    {
        "employee_name": "Sarah Wilson",
        "employee_salary": "85,000",
        "employee_position": "HR Specialist",
        "employee_start_date": "June 1, 2022",
        "employee_end_date": "May 31, 2023",
        "employee_department": "Human Resources"
    },
    {
        "employee_name": "Robert Martinez",
        "employee_salary": "95,000",
        "employee_position": "Finance Manager",
        "employee_start_date": "July 1, 2022",
        "employee_end_date": "June 30, 2023",
        "employee_department": "Finance"
    },
    {
        "employee_name": "Olivia Taylor",
        "employee_salary": "105,000",
        "employee_position": "Sales Manager",
        "employee_start_date": "August 1, 2022",
        "employee_end_date": "July 31, 2023",
        "employee_department": "Sales"
    },
    {
        "employee_name": "William Anderson",
        "employee_salary": "75,000",
        "employee_position": "Customer Support Specialist",
        "employee_start_date": "September 1, 2022",
        "employee_end_date": "August 31, 2023",
        "employee_department": "Customer Support"
    },
    {
        "employee_name": "Ava Thomas",
        "employee_salary": "65,000",
        "employee_position": "Administrative Assistant",
        "employee_start_date": "October 1, 2022",
        "employee_end_date": "September 30, 2023",
        "employee_department": "Administration"
    }
]

employee_contract_prompt = "Employee contracts outline the terms and conditions of employment between an employer and an employee. They typically include details such as the employee's position and responsibilities, compensation and benefits, work hours, termination conditions, confidentiality agreements, intellectual property rights, and compliance with company policies and procedures. These contracts ensure clarity and protection for both parties involved in the employment relationship."
employee_esops_prompt = "Employee stock ownership plans (ESOPs) are a type of employee benefit plan that provides employees with an ownership interest in the company. They typically include details such as the allocation of shares to employees, vesting schedules, eligibility criteria, valuation methods, and the rights and responsibilities of participating employees. These plans align the interests of employees with those of the company, fostering a sense of ownership and commitment."
employee_handbook_prompt = "Employee handbooks are comprehensive guides that provide employees with information about company policies, procedures, benefits, and expectations. They typically include details such as the company's mission and values, code of conduct, anti-discrimination and harassment policies, leave and attendance policies, performance management processes, and other relevant information. These handbooks serve as a valuable resource for employees, helping them understand their rights and responsibilities within the organization."
employee_payslip_prompt = "Employee payslips are documents that provide employees with a detailed breakdown of their earnings and deductions for a specific pay period. They typically include details such as the employee's basic salary, allowances, bonuses, taxes, insurance contributions, and net pay. These documents serve as a record of the employee's compensation and are essential for financial planning and compliance with tax regulations."

employee_contract_template = \
'''
# Employment Contract

## Employee Information:
- **Employee Name:** {employee_name}
- **Position:** {employee_position}
- **Department:** {employee_department}

## Terms and Conditions:
- **Responsibilities:** {employee_responsibilities}
- **Compensation:** {employee_compensation}
- **Benefits:** {employee_benefits}
- **Work Hours:** {employee_work_hours}
- **Termination Conditions:** {employee_termination_conditions}
- **Confidentiality Agreement:** {employee_confidentiality_agreement}
- **Intellectual Property Rights:** {employee_ip_rights}
- **Compliance with Company Policies:** {employee_company_policies}

This employment contract is entered into between {employer_name} (hereinafter referred to as "Employer") and {employee_name} (hereinafter referred to as "Employee") on {contract_date}.

This contract outlines the terms and conditions of employment for the Employee and is effective as of the start date of {start_date}. Both the Employer and Employee agree to abide by the terms set forth in this contract.
'''

employee_contract_list = [
    {
        "employee_name": "John Doe",
        "employee_position": "Software Engineer",
        "employee_department": "Engineering",
        "employee_responsibilities": "Developing and maintaining software applications.",
        "employee_compensation": "$100,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "January 1, 2022",
        "start_date": "January 1, 2022"
    },
    # create such a dictionary for 20 employees with varying roles in different departments
    {
        "employee_name": "Jane Smith",
        "employee_position": "Marketing Specialist",
        "employee_department": "Marketing",
        "employee_responsibilities": "Developing and executing marketing campaigns.",
        "employee_compensation": "$80,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "February 1, 2022",
        "start_date": "February 1, 2022"
    },
    {
        "employee_name": "Michael Johnson",
        "employee_position": "Product Manager",
        "employee_department": "Product Management",
        "employee_responsibilities": "Leading product development and strategy.",
        "employee_compensation": "$120,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "March 1, 2022",
        "start_date": "March 1, 2022"
    },
    {
        "employee_name": "Emily Brown",
        "employee_position": "UX Designer",
        "employee_department": "Design",
        "employee_responsibilities": "Designing user interfaces and experiences.",
        "employee_compensation": "$90,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "April 1, 2022",
        "start_date": "April 1, 2022"
    },
    {
        "employee_name": "David Lee",
        "employee_position": "Data Analyst",
        "employee_department": "Data Analytics",
        "employee_responsibilities": "Analyzing and interpreting data for insights.",
        "employee_compensation": "$110,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "May 1, 2022",
        "start_date": "May 1, 2022"
    },
    {
        "employee_name": "Sarah Wilson",
        "employee_position": "HR Specialist",
        "employee_department": "Human Resources",
        "employee_responsibilities": "Managing employee relations and recruitment.",
        "employee_compensation": "$85,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "June 1, 2022",
        "start_date": "June 1, 2022"
    },
    {
        "employee_name": "Robert Martinez",
        "employee_position": "Finance Manager",
        "employee_department": "Finance",
        "employee_responsibilities": "Overseeing financial operations and reporting.",
        "employee_compensation": "$95,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "July 1, 2022",
        "start_date": "July 1, 2022"
    },
    {
        "employee_name": "Olivia Taylor",
        "employee_position": "Sales Manager",
        "employee_department": "Sales",
        "employee_responsibilities": "Leading sales strategy and operations.",
        "employee_compensation": "$105,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "August 1, 2022",
        "start_date": "August 1, 2022"
    },
    {
        "employee_name": "William Anderson",
        "employee_position": "Customer Support Specialist",
        "employee_department": "Customer Support",
        "employee_responsibilities": "Assisting customers with product inquiries and issues.",
        "employee_compensation": "$75,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "September 1, 2022",
        "start_date": "September 1, 2022"
    },
    {
        "employee_name": "Ava Thomas",
        "employee_position": "Administrative Assistant",
        "employee_department": "Administration",
        "employee_responsibilities": "Providing administrative support to the team.",
        "employee_compensation": "$65,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "October 1, 2022",
        "start_date": "October 1, 2022"
    },
    {
        "employee_name": "Sophia Garcia",
        "employee_position": "Legal Counsel",
        "employee_department": "Legal",
        "employee_responsibilities": "Providing legal advice and support to the company.",
        "employee_compensation": "$125,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "November 1, 2022",
        "start_date": "November 1, 2022"
    },
    {
        "employee_name": "Ethan Rodriguez",
        "employee_position": "Security Officer",
        "employee_department": "Security",
        "employee_responsibilities": "Ensuring the safety and security of the company's premises.",
        "employee_compensation": "$70,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "December 1, 2022",
        "start_date": "December 1, 2022"
    },
    {
        "employee_name": "Mia Hernandez",
        "employee_position": "Public Relations Manager",
        "employee_department": "Public Relations",
        "employee_responsibilities": "Managing the company's public relations and communications.",
        "employee_compensation": "$110,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "January 1, 2023",
        "start_date": "January 1, 2023"
    },
    {
        "employee_name": "Lucas Martinez",
        "employee_position": "Quality Assurance Specialist",
        "employee_department": "Quality Assurance",
        "employee_responsibilities": "Ensuring the quality of the company's products and services.",
        "employee_compensation": "$80,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "February 1, 2023",
        "start_date": "February 1, 2023"
    },
    {
        "employee_name": "Luna Nguyen",
        "employee_position": "Content Creator",
        "employee_department": "Content Creation",
        "employee_responsibilities": "Producing engaging and creative content for the company.",
        "employee_compensation": "$75,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "March 1, 2023",
        "start_date": "March 1, 2023"
    },
    {
        "employee_name": "Leo Kim",
        "employee_position": "Data Scientist",
        "employee_department": "Data Science",
        "employee_responsibilities": "Analyzing and interpreting data for insights.",
        "employee_compensation": "$100,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "April 1, 2023",
        "start_date": "April 1, 2023"
    },
    {
        "employee_name": "Zoe Lee",
        "employee_position": "Customer Success Manager",
        "employee_department": "Customer Success",
        "employee_responsibilities": "Ensuring customer satisfaction and retention.",
        "employee_compensation": "$90,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "May 1, 2023",
        "start_date": "May 1, 2023"
    },
    {
        "employee_name": "Eva Kim",
        "employee_position": "Content Moderator",
        "employee_department": "Content Moderation",
        "employee_responsibilities": "Monitoring and moderating user-generated content.",
        "employee_compensation": "$80,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "June 1, 2023",
        "start_date": "June 1, 2023"
    },
    {
        "employee_name": "Max Nguyen",
        "employee_position": "Software Developer",
        "employee_department": "Engineering",
        "employee_responsibilities": "Developing and maintaining software applications.",
        "employee_compensation": "$95,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "July 1, 2023",
        "start_date": "July 1, 2023"
    },
    {
        "employee_name": "Liam Kim",
        "employee_position": "Data Engineer",
        "employee_department": "Data Engineering",
        "employee_responsibilities": "Designing and maintaining data infrastructure.",
        "employee_compensation": "$105,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "August 1, 2023",
        "start_date": "August 1, 2023"
    },
    {
        "employee_name": "Mila Lee",
        "employee_position": "Product Designer",
        "employee_department": "Design",
        "employee_responsibilities": "Designing user interfaces and experiences.",
        "employee_compensation": "$85,000 per year",
        "employee_benefits": "Health insurance, retirement plan",
        "employee_work_hours": "40 hours per week",
        "employee_termination_conditions": "30 days' notice",
        "employee_confidentiality_agreement": "Yes",
        "employee_ip_rights": "Company-owned",
        "employee_company_policies": "Compliance required",
        "employer_name": "Instagram",
        "contract_date": "September 1, 2023",
        "start_date": "September 1, 2023"
    },
]

employee_esop_template = \
'''
# Employee Stock Ownership Plan (ESOP)

## Employee Information:
- **Employee Name:** {employee_name}
- **Position:** {employee_position}
- **Department:** {employee_department}

## ESOP Details:
- **Allocation of Shares:** {esop_allocation}
- **Vesting Schedule:** {esop_vesting}
- **Eligibility Criteria:** {esop_criteria}
- **Valuation Methods:** {esop_valuation}
- **Rights and Responsibilities:** {esop_rights_responsibilities}

This Employee Stock Ownership Plan (ESOP) is entered into between {employer_name} (hereinafter referred to as "Employer") and {employee_name} (hereinafter referred to as "Employee") on {contract_date}.

The ESOP details the allocation of shares, vesting schedule, eligibility criteria, valuation methods, and the rights and responsibilities of participating employees. This plan aims to provide employees with an ownership interest in the company, aligning their interests with that of the company.
'''

# create a list for esop document template for each employee in employee_contract_list
employee_esop_list = [
    {
        "employee_name": "John Doe",
        "employee_position": "Software Engineer",
        "employee_department": "Engineering",
        "esop_allocation": "100 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "January 1, 2022"
    },
    # create such a dictionary for 20 employees with varying roles in different departments
    {
        "employee_name": "Jane Smith",
        "employee_position": "Marketing Specialist",
        "employee_department": "Marketing",
        "esop_allocation": "80 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "February 1, 2022"
    },
    {
        "employee_name": "Michael Johnson",
        "employee_position": "Product Manager",
        "employee_department": "Product Management",
        "esop_allocation": "120 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "March 1, 2022"
    },
    {
        "employee_name": "Emily Brown",
        "employee_position": "UX Designer",
        "employee_department": "Design",
        "esop_allocation": "90 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "April 1, 2022"
    },
    {
        "employee_name": "David Lee",
        "employee_position": "Data Analyst",
        "employee_department": "Data Analytics",
        "esop_allocation": "110 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "May 1, 2022"
    },
    {
        "employee_name": "Sarah Wilson",
        "employee_position": "HR Specialist",
        "employee_department": "Human Resources",
        "esop_allocation": "85 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "June 1, 2022"
    },
    {
        "employee_name": "Robert Martinez",
        "employee_position": "Finance Manager",
        "employee_department": "Finance",
        "esop_allocation": "95 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "July 1, 2022"
    },
    {
        "employee_name": "Olivia Taylor",
        "employee_position": "Sales Manager",
        "employee_department": "Sales",
        "esop_allocation": "105 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "August 1, 2022"
    },
    {
        "employee_name": "William Anderson",
        "employee_position": "Customer Support Specialist",
        "employee_department": "Customer Support",
        "esop_allocation": "75 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "September 1, 2022"
    },
    {
        "employee_name": "Ava Thomas",
        "employee_position": "Administrative Assistant",
        "employee_department": "Administration",
        "esop_allocation": "65 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "October 1, 2022"
    },
    {
        "employee_name": "Sophia Garcia",
        "employee_position": "Legal Counsel",
        "employee_department": "Legal",
        "esop_allocation": "125 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "November 1, 2022"
    },
    {
        "employee_name": "Ethan Rodriguez",
        "employee_position": "Security Officer",
        "employee_department": "Security",
        "esop_allocation": "70 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "December 1, 2022"
    },
    {
        "employee_name": "Mia Hernandez",
        "employee_position": "Public Relations Manager",
        "employee_department": "Public Relations",
        "esop_allocation": "110 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "January 1, 2023"
    },
    {
        "employee_name": "Lucas Martinez",
        "employee_position": "Quality Assurance Specialist",
        "employee_department": "Quality Assurance",
        "esop_allocation": "80 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "February 1, 2023"
    },
    {
        "employee_name": "Luna Nguyen",
        "employee_position": "Content Creator",
        "employee_department": "Content Creation",
        "esop_allocation": "75 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "March 1, 2023"
    },
    {
        "employee_name": "Leo Kim",
        "employee_position": "Data Scientist",
        "employee_department": "Data Science",
        "esop_allocation": "100 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "April 1, 2023"
    },
    {
        "employee_name": "Zoe Lee",
        "employee_position": "Customer Success Manager",
        "employee_department": "Customer Success",
        "esop_allocation": "90 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "May 1, 2023"
    },
    {
        "employee_name": "Eva Kim",
        "employee_position": "Content Moderator",
        "employee_department": "Content Moderation",
        "esop_allocation": "80 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "June 1, 2023"
    },
    {
        "employee_name": "Max Nguyen",
        "employee_position": "Software Developer",
        "employee_department": "Engineering",
        "esop_allocation": "95 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "July 1, 2023"
    },
    {
        "employee_name": "Liam Kim",
        "employee_position": "Data Engineer",
        "employee_department": "Data Engineering",
        "esop_allocation": "105 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "August 1, 2023"
    },
    {
        "employee_name": "Mila Lee",
        "employee_position": "Product Designer",
        "employee_department": "Design",
        "esop_allocation": "85 shares",
        "esop_vesting": "4-year vesting schedule",
        "esop_criteria": "Full-time employment",
        "esop_valuation": "Fair market value",
        "esop_rights_responsibilities": "Voting rights, dividend entitlement",
        "employer_name": "Instagram",
        "contract_date": "September 1, 2023"
    },
]

employee_payslip_template = \
'''
# Employee Payslip

## Employee Information:
- **Employee Name:** {employee_name}
- **Employee ID:** {employee_id}
- **Position:** {employee_position}
- **Department:** {employee_department}

## Pay Period:
- **Start Date:** {pay_period_start_date}
- **End Date:** {pay_period_end_date}

## Earnings:
- **Basic Salary:** {earnings_basic_salary}
- **Allowances:** {earnings_allowances}
- **Bonuses:** {earnings_bonuses}
- **Total Earnings:** {earnings_total}

## Deductions:
- **Taxes:** {deductions_taxes}
- **Insurance Contributions:** {deductions_insurance}
- **Other Deductions:** {deductions_other}
- **Total Deductions:** {deductions_total}

## Net Pay:
- **Net Pay:** {net_pay}

This Employee Payslip is issued to {employee_name} for the pay period from {pay_period_start_date} to {pay_period_end_date}. It provides a detailed breakdown of earnings, deductions, and the net pay for the specified period.
'''

employee_payslip_list = [
    {
        "employee_name": "John Doe",
        "employee_id": "12345",
        "employee_position": "Software Engineer",
        "employee_department": "Engineering",
        "pay_period_start_date": "January 1, 2022",
        "pay_period_end_date": "January 15, 2022",
        "earnings_basic_salary": "$4,166.67",
        "earnings_allowances": "$500.00",
        "earnings_bonuses": "$1,000.00",
        "earnings_total": "$5,666.67",
        "deductions_taxes": "$1,000.00",
        "deductions_insurance": "$200.00",
        "deductions_other": "$100.00",
        "deductions_total": "$1,300.00",
        "net_pay": "$4,366.67"
    },
    # create such a dictionary for 20 employees with varying roles in different departments
    {
        "employee_name": "Jane Smith",
        "employee_id": "12346",
        "employee_position": "Marketing Specialist",
        "employee_department": "Marketing",
        "pay_period_start_date": "February 1, 2022",
        "pay_period_end_date": "February 15, 2022",
        "earnings_basic_salary": "$3,333.33",
        "earnings_allowances": "$400.00",
        "earnings_bonuses": "$800.00",
        "earnings_total": "$4,533.33",
        "deductions_taxes": "$800.00",
        "deductions_insurance": "$160.00",
        "deductions_other": "$80.00",
        "deductions_total": "$1,040.00",
        "net_pay": "$3,493.33"
    },
    {
        "employee_name": "Michael Johnson",
        "employee_id": "12347",
        "employee_position": "Product Manager",
        "employee_department": "Product Management",
        "pay_period_start_date": "March 1, 2022",
        "pay_period_end_date": "March 15, 2022",
        "earnings_basic_salary": "$5,000.00",
        "earnings_allowances": "$600.00",
        "earnings_bonuses": "$1,200.00",
        "earnings_total": "$6,800.00",
        "deductions_taxes": "$1,200.00",
        "deductions_insurance": "$240.00",
        "deductions_other": "$120.00",
        "deductions_total": "$1,560.00",
        "net_pay": "$5,240.00"
    },
    {
        "employee_name": "Emily Brown",
        "employee_id": "12348",
        "employee_position": "UX Designer",
        "employee_department": "Design",
        "pay_period_start_date": "April 1, 2022",
        "pay_period_end_date": "April 15, 2022",
        "earnings_basic_salary": "$3,750.00",
        "earnings_allowances": "$450.00",
        "earnings_bonuses": "$900.00",
        "earnings_total": "$5,100.00",
        "deductions_taxes": "$900.00",
        "deductions_insurance": "$180.00",
        "deductions_other": "$90.00",
        "deductions_total": "$1,170.00",
        "net_pay": "$3,930.00"
    },
    {
        "employee_name": "David Lee",
        "employee_id": "12349",
        "employee_position": "Data Analyst",
        "employee_department": "Data Analytics",
        "pay_period_start_date": "May 1, 2022",
        "pay_period_end_date": "May 15, 2022",
        "earnings_basic_salary": "$4,583.33",
        "earnings_allowances": "$550.00",
        "earnings_bonuses": "$1,100.00",
        "earnings_total": "$6,233.33",
        "deductions_taxes": "$1,100.00",
        "deductions_insurance": "$220.00",
        "deductions_other": "$110.00",
        "deductions_total": "$1,430.00",
        "net_pay": "$4,803.33"
    },
    {
        "employee_name": "Sarah Wilson",
        "employee_id": "12350",
        "employee_position": "HR Specialist",
        "employee_department": "Human Resources",
        "pay_period_start_date": "June 1, 2022",
        "pay_period_end_date": "June 15, 2022",
        "earnings_basic_salary": "$3,541.67",
        "earnings_allowances": "$425.00",
        "earnings_bonuses": "$850.00",
        "earnings_total": "$4,816.67",
        "deductions_taxes": "$850.00",
        "deductions_insurance": "$170.00",
        "deductions_other": "$85.00",
        "deductions_total": "$1,105.00",
        "net_pay": "$3,711.67"
    },
    {
        "employee_name": "Robert Martinez",
        "employee_id": "12351",
        "employee_position": "Finance Manager",
        "employee_department": "Finance",
        "pay_period_start_date": "July 1, 2022",
        "pay_period_end_date": "July 15, 2022",
        "earnings_basic_salary": "$3,958.33",
        "earnings_allowances": "$475.00",
        "earnings_bonuses": "$950.00",
        "earnings_total": "$5,383.33",
        "deductions_taxes": "$950.00",
        "deductions_insurance": "$190.00",
        "deductions_other": "$95.00",
        "deductions_total": "$1,235.00",
        "net_pay": "$4,148.33"
    },
    {
        "employee_name": "Olivia Taylor",
        "employee_id": "12352",
        "employee_position": "Sales Manager",
        "employee_department": "Sales",
        "pay_period_start_date": "August 1, 2022",
        "pay_period_end_date": "August 15, 2022",
        "earnings_basic_salary": "$4,375.00",
        "earnings_allowances": "$525.00",
        "earnings_bonuses": "$1,050.00",
        "earnings_total": "$5,950.00",
        "deductions_taxes": "$1,050.00",
        "deductions_insurance": "$210.00",
        "deductions_other": "$105.00",
        "deductions_total": "$1,365.00",
        "net_pay": "$4,585.00"
    },
    {
        "employee_name": "William Anderson",
        "employee_id": "12353",
        "employee_position": "Customer Support Specialist",
        "employee_department": "Customer Support",
        "pay_period_start_date": "September 1, 2022",
        "pay_period_end_date": "September 15, 2022",
        "earnings_basic_salary": "$3,125.00",
        "earnings_allowances": "$375.00",
        "earnings_bonuses": "$750.00",
        "earnings_total": "$4,250.00",
        "deductions_taxes": "$750.00",
        "deductions_insurance": "$150.00",
        "deductions_other": "$75.00",
        "deductions_total": "$975.00",
        "net_pay": "$3,275.00"
    },
    {
        "employee_name": "Ava Thomas",
        "employee_id": "12354",
        "employee_position": "Administrative Assistant",
        "employee_department": "Administration",
        "pay_period_start_date": "October 1, 2022",
        "pay_period_end_date": "October 15, 2022",
        "earnings_basic_salary": "$2,916.67",
        "earnings_allowances": "$350.00",
        "earnings_bonuses": "$700.00",
        "earnings_total": "$3,966.67",
        "deductions_taxes": "$700.00",
        "deductions_insurance": "$140.00",
        "deductions_other": "$70.00",
        "deductions_total": "$910.00",
        "net_pay": "$3,056.67"
    },
    {
        "employee_name": "Sophia Garcia",
        "employee_id": "12355",
        "employee_position": "Legal Counsel",
        "employee_department": "Legal",
        "pay_period_start_date": "November 1, 2022",
        "pay_period_end_date": "November 15, 2022",
        "earnings_basic_salary": "$5,208.33",
        "earnings_allowances": "$625.00",
        "earnings_bonuses": "$1,250.00",
        "earnings_total": "$7,083.33",
        "deductions_taxes": "$1,250.00",
        "deductions_insurance": "$250.00",
        "deductions_other": "$125.00",
        "deductions_total": "$1,625.00",
        "net_pay": "$5,458.33"
    },
    {
        "employee_name": "Ethan Rodriguez",
        "employee_id": "12356",
        "employee_position": "Security Officer",
        "employee_department": "Security",
        "pay_period_start_date": "December 1, 2022",
        "pay_period_end_date": "December 15, 2022",
        "earnings_basic_salary": "$2,916.67",
        "earnings_allowances": "$350.00",
        "earnings_bonuses": "$700.00",
        "earnings_total": "$3,966.67",
        "deductions_taxes": "$700.00",
        "deductions_insurance": "$140.00",
        "deductions_other": "$70.00",
        "deductions_total": "$910.00",
        "net_pay": "$3,056.67"
    },
    {
        "employee_name": "Mia Hernandez",
        "employee_id": "12357",
        "employee_position": "Public Relations Manager",
        "employee_department": "Public Relations",
        "pay_period_start_date": "January 1, 2023",
        "pay_period_end_date": "January 15, 2023",
        "earnings_basic_salary": "$4,166.67",
        "earnings_allowances": "$500.00",
        "earnings_bonuses": "$1,000.00",
        "earnings_total": "$5,666.67",
        "deductions_taxes": "$1,000.00",
        "deductions_insurance": "$200.00",
        "deductions_other": "$100.00",
        "deductions_total": "$1,300.00",
        "net_pay": "$4,366.67"
    },
    {
        "employee_name": "Lucas Martinez",
        "employee_id": "12358",
        "employee_position": "Quality Assurance Specialist",
        "employee_department": "Quality Assurance",
        "pay_period_start_date": "February 1, 2023",
        "pay_period_end_date": "February 15, 2023",
        "earnings_basic_salary": "$3,333.33",
        "earnings_allowances": "$400.00",
        "earnings_bonuses": "$800.00",
        "earnings_total": "$4,533.33",
        "deductions_taxes": "$800.00",
        "deductions_insurance": "$160.00",
        "deductions_other": "$80.00",
        "deductions_total": "$1,040.00",
        "net_pay": "$3,493.33"
    },
    {
        "employee_name": "Luna Nguyen",
        "employee_id": "12359",
        "employee_position": "Content Creator",
        "employee_department": "Content Creation",
        "pay_period_start_date": "March 1, 2023",
        "pay_period_end_date": "March 15, 2023",
        "earnings_basic_salary": "$3,125.00",
        "earnings_allowances": "$375.00",
        "earnings_bonuses": "$750.00",
        "earnings_total": "$4,250.00",
        "deductions_taxes": "$750.00",
        "deductions_insurance": "$150.00",
        "deductions_other": "$75.00",
        "deductions_total": "$975.00",
        "net_pay": "$3,275.00"
    },
    {
        "employee_name": "Leo Kim",
        "employee_id": "12360",
        "employee_position": "Data Scientist",
        "employee_department": "Data Science",
        "pay_period_start_date": "April 1, 2023",
        "pay_period_end_date": "April 15, 2023",
        "earnings_basic_salary": "$4,166.67",
        "earnings_allowances": "$500.00",
        "earnings_bonuses": "$1,000.00",
        "earnings_total": "$5,666.67",
        "deductions_taxes": "$1,000.00",
        "deductions_insurance": "$200.00",
        "deductions_other": "$100.00",
        "deductions_total": "$1,300.00",
        "net_pay": "$4,366.67"
    },
    {
        "employee_name": "Zoe Lee",
        "employee_id": "12361",
        "employee_position": "Customer Success Manager",
        "employee_department": "Customer Success",
        "pay_period_start_date": "May 1, 2023",
        "pay_period_end_date": "May 15, 2023",
        "earnings_basic_salary": "$3,750.00",
        "earnings_allowances": "$450.00",
        "earnings_bonuses": "$900.00",
        "earnings_total": "$5,100.00",
        "deductions_taxes": "$900.00",
        "deductions_insurance": "$180.00",
        "deductions_other": "$90.00",
        "deductions_total": "$1,170.00",
        "net_pay": "$3,930.00"
    },
    {
        "employee_name": "Eva Kim",
        "employee_id": "12362",
        "employee_position": "Content Moderator",
        "employee_department": "Content Moderation",
        "pay_period_start_date": "June 1, 2023",
        "pay_period_end_date": "June 15, 2023",
        "earnings_basic_salary": "$3,333.33",
        "earnings_allowances": "$400.00",
        "earnings_bonuses": "$800.00",
        "earnings_total": "$4,533.33",
        "deductions_taxes": "$800.00",
        "deductions_insurance": "$160.00",
        "deductions_other": "$80.00",
        "deductions_total": "$1,040.00",
        "net_pay": "$3,493.33"
    },
    {
        "employee_name": "Max Nguyen",
        "employee_id": "12363",
        "employee_position": "Software Developer",
        "employee_department": "Engineering",
        "pay_period_start_date": "July 1, 2023",
        "pay_period_end_date": "July 15, 2023",
        "earnings_basic_salary": "$3,958.33",
        "earnings_allowances": "$475.00",
        "earnings_bonuses": "$950.00",
        "earnings_total": "$5,383.33",
        "deductions_taxes": "$950.00",
        "deductions_insurance": "$190.00",
        "deductions_other": "$95.00",
        "deductions_total": "$1,235.00",
        "net_pay": "$4,148.33"
    },
    {
        "employee_name": "Liam Kim",
        "employee_id": "12364",
        "employee_position": "Data Engineer",
        "employee_department": "Data Engineering",
        "pay_period_start_date": "August 1, 2023",
        "pay_period_end_date": "August 15, 2023",
        "earnings_basic_salary": "$4,375.00",
        "earnings_allowances": "$525.00",
        "earnings_bonuses": "$1,050.00",
        "earnings_total": "$5,950.00",
        "deductions_taxes": "$1,050.00",
        "deductions_insurance": "$210.00",
        "deductions_other": "$105.00",
        "deductions_total": "$1,365.00",
        "net_pay": "$4,585.00"
    },
    {
        "employee_name": "Mila Lee",
        "employee_id": "12365",
        "employee_position": "Product Designer",
        "employee_department": "Design",
        "pay_period_start_date": "September 1, 2023",
        "pay_period_end_date": "September 15, 2023",
        "earnings_basic_salary": "$3,541.67",
        "earnings_allowances": "$425.00",
        "earnings_bonuses": "$850.00",
        "earnings_total": "$4,816.67",
        "deductions_taxes": "$850.00",
        "deductions_insurance": "$170.00",
        "deductions_other": "$85.00",
        "deductions_total": "$1,105.00",
        "net_pay": "$3,711.67"
    },
]

employee_contract_prompts_list = [
    {
        "doc_category": "Employee Contract",
        "doc_title": "Employment Contract",
        "doc_description": employee_contract_prompt
    },
    {
        "doc_category": "Employee Contract",
        "doc_title": "Employee Stock Ownership Plan (ESOP)",
        "doc_description": employee_esops_prompt
    },
    {
        "doc_category": "Employee Contract",
        "doc_title": "Employee Handbook",
        "doc_description": employee_handbook_prompt
    },
    {
        "doc_category": "Employee Contract",
        "doc_title": "Employee Payslip",
        "doc_description": employee_payslip_prompt
    }
]

# Category of document: Financial Documents

income_statement_prompt = "An income statement summarizes a company's revenues, expenses, and net income over a specific period. It typically includes revenue, cost of goods sold (COGS), gross profit, operating expenses, operating income, non-operating items, income before taxes, income taxes, and net income. This financial report provides insights into the company's profitability and financial performance."
balance_sheet_prompt = "A balance sheet provides a snapshot of a company's financial position at a specific point in time. It typically includes assets, liabilities, and shareholders' equity. This financial report provides insights into the company's liquidity, solvency, and financial health."
tax_return_prompt = "A tax return is a form filed with a tax authority that reports income, expenses, and other relevant financial information. It typically includes details such as income sources, deductions, credits, taxes owed, and refunds. This document is essential for compliance with tax regulations and the calculation of tax liabilities."

financial_documents_prompts_list = [
    {
        "doc_category": "Financial Documents",
        "doc_title": "Income Statement",
        "doc_description": income_statement_prompt
    },
    {
        "doc_category": "Financial Documents",
        "doc_title": "Balance Sheet",
        "doc_description": balance_sheet_prompt
    },
    {
        "doc_category": "Financial Documents",
        "doc_title": "Tax Return",
        "doc_description": tax_return_prompt
    }
]

# Category of document: Business documents

progress_report_prompt = "A progress report for a company provides updates on ongoing projects and goals. It typically includes achievements, current work status, key metrics, challenges, action plans, resource allocation, financial updates, and conclusions. This document ensures transparency, accountability, and alignment across teams while facilitating adjustments to strategies to achieve organizational goals. Make up multiple projects that seem realistic with the company information given, and make their status updates in a MarkDown table format."
business_proposal_prompt = "A business proposal outlines a company's offer to provide products or services to a potential client. It typically includes an executive summary, company overview, problem statement, proposed solution, pricing, terms and conditions, timeline, and contact information. This document serves as a formal communication tool to attract new clients and secure business opportunities. Make up 3 business proposals for different services that seem realistic with the company information given in a MarkDown format."
marketing_plan_prompt = "A marketing plan outlines a company's strategy for promoting its products or services. It typically includes market analysis, target audience, marketing objectives, strategies, tactics, budget, timeline, and performance metrics. This document serves as a roadmap for marketing activities, ensuring alignment with business goals and customer needs. Create these marketing plans for each of the business proposals you made earlier in a MarkDown format."

business_documents_prompts_list = [
    {
        "doc_category": "Business Documents",
        "doc_title": "Progress Report",
        "doc_description": progress_report_prompt
    },
    {
        "doc_category": "Business Documents",
        "doc_title": "Business Proposal",
        "doc_description": business_proposal_prompt
    },
    {
        "doc_category": "Business Documents",
        "doc_title": "Marketing Plan",
        "doc_description": marketing_plan_prompt
    }
]